apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  namespace: infisical
  labels:
    app: infisical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical
  template:
    metadata:
      labels:
        app: infisical
    spec:
      containers:
      - name: infisical
        image: infisical/infisical:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: ENCRYPTION_KEY
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: AUTH_SECRET
        - name: DB_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: DB_CONNECTION_URI
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: infisical-secrets
              key: REDIS_URL
        - name: SITE_URL
          value: "https://secrets.0xaace.xyz"
        - name: TELEMETRY_ENABLED
          value: "false"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /api/status
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
