apiVersion: v1
kind: Service
metadata:
  name: infisical-redis
  namespace: infisical
  labels:
    app: infisical-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: infisical-redis
