apiVersion: batch/v1
kind: Job
metadata:
  name: phone-games-migration
  namespace: phone-games
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"  # Run before everything else (wave 0 is default)
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for PostgreSQL to be ready..."
            until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
              echo "PostgreSQL is unavailable - sleeping"
              sleep 2
            done
            echo "PostgreSQL is ready!"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        - name: DB_HOST
          value: "postgres"  # Postgres service name in the same namespace
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"  # Update with your actual postgres user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      containers:
      - name: migration
        image: xaace/phone-games-server:latest
        command: ["sh", "-c"]
        args:
          - |
            echo "Running database migrations..."
            cd /app/packages/db/prisma
            prisma migrate deploy
            echo "Migrations completed successfully!"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
