apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    targetRevision: 0.10.1  # You can use a specific version or "0.*" for latest minor version
    chart: secrets-operator
    helm:
      values: |
        controllerManager:
          manager:
            env:
            - name: INFISICAL_URL
              value: "http://infisical.infisical.svc.cluster.local:8080"

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
